spring:
  datasource:
    url: jdbc:mysql://localhost:3306/record?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource # 修改数据库连接池为 Druid
    #连接池的配置信息
#    druid:
    #初始化大小，最小，最大
#    initialSize: 5
#    minIdle: 5
##    maxActive: 20
#    maxWait: 60000    #配置获取连接等待超时的时间
##    maxEvictableIdleTimeMillis: 90000
#    timeBetweenEvictionRunsMillis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    minEvictableIdleTimeMillis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
#    poolPreparedStatements: true  #打开PSCache，并且指定每个连接上PSCache的大小
##    maxPoolPreparedStatementPerConnectionSize: 20
#      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    chat1:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/chat1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#      username: root
#      password: admin
#    chat2:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      enabled: true
#      jdbc-url: jdbc:mysql://localhost:3306/chat2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#      username: root
#      password: admin
#    chat3:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      enabled: true
#      jdbc-url: jdbc:mysql://localhost:3306/chat3?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#      username: root
#      password: admin
