server:
  port: 443
  ssl:
    key-store: tomcat.keystore
    key-store-password: tomcat
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  profiles:
    active: datasource
share:
  path:
file-service:
  profile: d:/profile
