const url={
    http:"http",
    https:"https",
    ws:"ws",
    wss:"wss",
    ip:"192.168.1.63",
    tworoot:"//",
    port80:"80",
    port443:"443",
    colon:":",
    home:"https://127.0.0.1",
    root:"/",
    websocket:"/websocket",
    user:"/user",
    login:"/login",
    update:"/update",
    password:"/password",
    file:"/file",
    get:"/get",
    all:"/all",
    read:"/read",
    blog:"/blog",
    img:"/img",
    upload:"/upload",
    new:"/new",
    delete:"/delete",
    record:"/record",
    add:"/add",

}

export default url;
